config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "members#index"

  resources :members, only: [:index, :new, :create, :edit, :destroy, :show]

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  before_action :sign, except: [:index, :show]

  def index 
    @members = Member.order("created_at DESC").page(params[:page]).per(2)
  end

  def new
    @member = Member.new 
  end
  
  def create 
    @members = Member.create(member_params)
    redirect_to root_path
  end

  def edit
    @member = Member.find(params[:id])
  end

  def destroy
    member = Member.find(params[:id])
    member.destroy
  end

  def show
    @members = Member.order("RAND()").limit(1)
  end

  private
  def member_params
    params.require(:member).permit(:id, :name, :birthplace, :birthday, :hobby, :message, :image)
  end

  def sign
    redirect_to action: :index unless user_signed_in?
  end
end
      

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title StaffIntroduction
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/members/_done.html.haml
.contents
  .content-box
    .content-box__style
      %p 登録完了

    .content-box__top
      = link_to "TOPに戻る", root_path, class: "content-box__top--font"
         
    

app/views/members/_footer.html.haml
.footer
  .footer-contents
  
    = link_to 'topに戻る', '#', class: 'footer-contents__box' 
      
    %p.footer-contents__box
      会社情報

    = link_to '朝礼担当', member_path(@members), class: 'footer-contents__box'
      
      
     
     
     

  

app/views/members/_header-image.html.haml
.header-image   

app/views/members/_header.html.haml
.header
  .header-contents
    .header-contents__name 
      株式会社 ○○○
    .header-contents__tel 
      TEL ○○○-○○○-○○○
      .header-contents__path 
        - if user_signed_in?
          .header_contents__path__in
            = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "post" 
        - else
          .header_contents__path__in
            = link_to "ログイン", new_user_session_path, class: "post"
            = link_to "新規登録", new_user_registration_path, class: 'post'

app/views/members/_main-member-box-list__left__name.html.haml
.main-member-box-list__left
  .main-member-box-list__left__name
    = link_to edit_member_path(member.id) do
      = image_tag member.image.url, size: '150x150', class: "main-member-box-list__left__name--image"
    .icon-class
      %p いいね！
      = fa_icon "thumbs-o-up", class: 'iine'
    %ul
      %li<      
        名前: 
        = member.name
        
      %li<
        出身地:
        = member.birthplace
        
      %li<
        生年月日:
        = member.birthday
        
      %li<
        特技:
        = member.hobby
        
      %li<
        メッセージ:
        = member.message
          

app/views/members/_main-navi.html.haml
.main-contents
  .main-content-box
    .main-content-box__font 
      STAFF INTRODUCTION
      %bottom
      = link_to new_member_path, class: "main-content-box__btn" do
        メンバー登録
      %p.main-content-box__add 
        〜 スタッフ紹介 〜

app/views/members/_main.html.haml
.main-member 
  = paginate(@members)
  .main-member-box
    .main-member-box-list
      - @members.each do |member| 
        = render partial: "main-member-box-list__left__name", locals: { member: member }
      

      

app/views/members/_post.html.haml
.post
  .post-box
    .post-member
      %p.post-member__list
        メンバー登録
    .post-form 
      = form_with model: @member, url: members_path do |f|
        .post-form__name 写真  
        = f.file_field :image, class: "post-form__boxes"
      
        .post-form__name 名前
        = f.text_field :name, class: "post-form__boxes"
          
        .post-form__name 出身地
        = f.select :birthplace, [["福岡", "福岡"], ["佐賀", "佐賀"], ["長崎", "長崎"], ["大分", "大分"], ["熊本", "熊本"], ["宮崎", "宮崎"], ["鹿児島", "鹿児島"], ["沖縄", "沖縄"]], include_blank: "選択して下さい"

        .post-form__name 生年月日
        = f.date_field :birthday, class: "post-form__boxes"

        .post-form__name 特技
        = f.text_field :hobby, class: "post-form__boxes"

        .post-form__name メッセージ
        = f.text_area :message, class: "post-form__box"
        
        .post-form__name
        = f.submit "登録", class: "post-form__boxes"
        

app/views/members/destroy.html.haml
.content
  .content__box
    = link_to root_path do
      %p 削除しました!!

app/views/members/edit.html.haml
.warapper
  = render 'members/header'
  = render 'members/header-image'
  .show-contents
    .show-box
      = image_tag @member.image.url, size: '300x300', class: "show-box__list"
      .icon-class
        %p いいね！
        = fa_icon "thumbs-o-up", class: 'iine'
      %ul
        %li    
          名前: 
          = @member.name
          
        %li
          出身地:
          = @member.birthplace
          
        %li
          生年月日:
          = @member.birthday
          
        %li
          特技:
          = @member.hobby
          
        %li
          メッセージ:
          = @member.message

    .fix
      = link_to "削除します", member_path(@member.id), method: :delete


       

app/views/members/index.html.haml
.warapper
  = render "header"
  = render "header-image"
  = render "main-navi"
  = render "main"
  = render "footer"

app/views/members/new.html.haml
.warapper
  = render "header"
  = render "header-image"
  = render "post"
  

app/views/members/show.html.haml
- @members.each do |member|
  .show-contents-box
    .show-contents
      .show-box
        = image_tag member.image.url, size: '300x300', class: "show-box__list"
        %ul
          %li    
            名前: 
            = member.name
            
          %li
            出身地:
            = member.birthplace
            
          %li
            生年月日:
            = member.birthday
            
          %li
            特技:
            = member.hobby
            
          %li
            メッセージ:
            = member.message

      